name: Test OS SDK CLI

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'The base url to use to download each platform'
        required: true
        default: 'https://github.com/NREL/OpenStudio/releases/download/v3.5.0'
      os_version:
        description: 'OpenStudio Version (e.g. 3.5.0)'
        required: true
        default: '3.5.0'
      os_prerelease_tag:
        description: 'Pre-release tag (e.g. -alpha, -rc1). Leave empty if none'
        required: false
        default: ''
      os_build_sha:
         description: 'OpenStudio Build sha (first 10 chars)'
         required: true
         default: 'bdbdbc9da6'

jobs:
  installer_ubuntu_2004:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal

    steps:
    - name: Download and install OS SDK installer
      shell: bash
      run: |
        set -x
        installer_url="${{ github.event.inputs.base_url}}/OpenStudio-${{ github.event.inputs.os_version}}${{ github.event.inputs.os_prerelease_tag}}%2B${{ github.event.inputs.os_build_sha}}-Ubuntu-18.04.deb"
        echo "Installer link: $installer_url"
        apt update && apt install -y wget
        wget $installer_url
        apt install -y ./OpenStudio*.deb
        openstudio openstudio_version
        echo "PATH=$PATH"

        OS_ROOT_DIR=/usr/local/openstudio-${{ github.event.inputs.os_version}}${{ github.event.inputs.os_prerelease_tag}}
        echo "OS_ROOT_DIR=$OS_ROOT_DIR" >> $GITHUB_ENV
        cp -R /usr/local/openstudio-3.4.0/Examples/compact_osw/*
        echo "puts ARGV" > test.rb

    - name: Basic CLI test
      shell: bash
      run: |
        set -x
        openstudio --help
        openstudio openstudio_version
        openstudio energyplus_version
        openstudio ruby_version
        openstudio -e "puts OpenStudio::Model::Model.new()"
        openstudio -e "require 'oga'; puts Oga::VERSION"
        openstudio execute_ruby_script test.rb -x arg2
        openstudio run -w compact_ruby_only.osw

    - name: Labs CLI Test
      shell: bash
      run: |
        set -x
        openstudio labs --help
        openstudio labs openstudio_version
        openstudio labs energyplus_version
        openstudio labs ruby_version
        openstudio labs python_version
        openstudio labs -e "puts OpenStudio::Model::Model.new()"
        openstudio labs -e "require 'oga'; puts Oga::VERSION"
        openstudio labs execute_ruby_script test.rb -- -x arg2
        openstudio labs run -w compact_ruby_only.osw
        openstudio labs run -w compact_python_only_twomeasures.osw
        openstudio labs run -w compact_ruby_and_python.osw || true

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: test loading the bindings in system ruby
      shell: bash
      run: |
        ruby --version
        ruby -I$OS_ROOT_DIR/Ruby/ -e "require 'openstudio'; puts OpenStudio.openStudioLongVersion()"

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: test loading the bindings in system python
      shell: bash
      run: |
        python --version
        python -c "import sys; sys.path.insert(0, '$OS_ROOT_DIR/python/'); import openstudio; print(openstudio.openStudioLongVersion())"

#    - uses: 8398a7/action-slack@v3
#      if: always() # Pick up events even if the job fails or is canceled.
#      with:
#        status: ${{ job.status }}
#        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
#      env:
#        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
