name: Repo dispatch

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'The base url to use to download each platform'
        required: true
        default: 'http://openstudio-ci-builds.s3-website-us-west-2.amazonaws.com/PR-4731'
      os_version:
        description: 'OpenStudio Version (e.g. 3.5.0)'
        required: true
        default: '3.5.0'
      os_prerelease_tag:
        description: 'Pre-release tag (e.g. -alpha, -rc1). Leave empty if none'
        required: false
      os_build_sha:
         description: 'OpenStudio Build sha (first 10 chars)'
         required: true
         default: 'f9e7e978ae'
  repository_dispatch:
    types: [on-demand-test]

jobs:
  installer_ubuntu_2004:
    runs-on: ubuntu-latest
    steps:
    - name: set up env variables
      if: ${{ github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        echo "BASE_URL=${{ github.event.inputs.base_url}}" >> $GITHUB_ENV
        echo "OS_VERSION=${{ github.event.inputs.os_version}}" >> $GITHUB_ENV
        echo "OS_PRERELEASE_TAG=${{ github.event.inputs.os_prerelease_tag}}" >> $GITHUB_ENV
        echo "OS_BUILD_SHA=${{ github.event.inputs.os_build_sha}}" >> $GITHUB_ENV

    - name: set up env variables
      if: ${{ github.event_name == 'repository_dispatch' }}
      shell: bash
      run: |
        echo "BASE_URL=${{ github.event.client_payload.base_url}}" >> $GITHUB_ENV
        echo "OS_VERSION=${{ github.event.client_payload.os_version}}" >> $GITHUB_ENV
        echo "OS_PRERELEASE_TAG=${{ github.client_payload.inputs.os_prerelease_tag}}" >> $GITHUB_ENV
        echo "OS_BUILD_SHA=${{ github.event.client_payload.os_build_sha}}" >> $GITHUB_ENV

    - name: echo
      shell: bash
      run: |
        echo BASE_URL=$BASE_URL
        echo OS_VERSION=$OS_VERSION
        echo OS_PRERELEASE_TAG=$OS_PRERELEASE_TAG
        echo OS_BUILD_SHA=$OS_BUILD_SHA
