name: Test CLI - Windows

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'The base url to use to download each platform'
        required: true
        default: 'http://openstudio-ci-builds.s3-website-us-west-2.amazonaws.com/PR-4731'
      os_version:
        description: 'OpenStudio Version (e.g. 3.5.0)'
        required: true
        default: '3.5.0'
      os_prerelease_tag:
        description: 'Pre-release tag (e.g. -alpha, -rc1). Leave empty if none'
        required: false
        default: ''
      os_build_sha:
        description: 'OpenStudio Build sha (first 10 chars)'
        required: true
        default: 'f9e7e978ae'

  repository_dispatch:
    types: [on-demand-test, on-demand-windows-test]

jobs:

  installer_windows_latest:
    runs-on: windows-latest

    steps:

    - name: Handle workflow_dispatch and repository_dispatch
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == 'workflow_dispatch' ]]; then
          echo "BASE_URL=${{ github.event.inputs.base_url}}" >> $GITHUB_ENV
          echo "OS_VERSION=${{ github.event.inputs.os_version}}" >> $GITHUB_ENV
          echo "OS_PRERELEASE_TAG=${{ github.event.inputs.os_prerelease_tag}}" >> $GITHUB_ENV
          echo "OS_BUILD_SHA=${{ github.event.inputs.os_build_sha}}" >> $GITHUB_ENV
        else
          # ${{ github.event_name == 'repository_dispatch' }}
          echo "BASE_URL=${{ github.event.client_payload.base_url}}" >> $GITHUB_ENV
          echo "OS_VERSION=${{ github.event.client_payload.os_version}}" >> $GITHUB_ENV
          echo "OS_PRERELEASE_TAG=${{ github.event.client_payload.os_prerelease_tag}}" >> $GITHUB_ENV
          echo "OS_BUILD_SHA=${{ github.event.client_payload.os_build_sha}}" >> $GITHUB_ENV
        fi;

    - name: Download and install OS SDK installer
      shell: bash
      run: |
        set -x
        installer_url="$BASE_URL/OpenStudio-$OS_VERSION$OS_PRERELEASE_TAG%2B$OS_BUILD_SHA-Windows.tar.gz"
        OS_DIR_NAME=OpenStudio-$OS_VERSION$OS_PRERELEASE_TAG+$OS_BUILD_SHA-Windows
        echo "OS_DIR_NAME=$OS_DIR_NAME" >> $GITHUB_ENV
        echo "Installer link: $installer_url"
        curl -SL $installer_url -o $OS_DIR_NAME.tar.gz
        ls
        tar xfz $OS_DIR_NAME.tar.gz

        OS_ROOT_DIR=$(pwd)/$OS_DIR_NAME
        echo "OS_ROOT_DIR=$OS_ROOT_DIR" >> $GITHUB_ENV
        cp -R $OS_ROOT_DIR/Examples/compact_osw/* .
        ls
        echo "puts ARGV" > test.rb

        export PATH="$OS_ROOT_DIR/bin:$PATH"
        echo "$OS_ROOT_DIR/bin" >> $GITHUB_PATH

        openstudio openstudio_version

        if openstudio labs; then
          echo "The Ruby CLI is the default"
          echo CLASSIC_SUBCOMMAND= >> $GITHUB_ENV
          echo LABS_SUBCOMMAND=labs >> $GITHUB_ENV
        else
          echo "The C++ CLI is the default"
          echo CLASSIC_SUBCOMMAND=classic >> $GITHUB_ENV
          echo LABS_SUBCOMMAND= >> $GITHUB_ENV
        fi

        echo "PATH=$PATH"

    - name: EnergyPlus itself works
      shell: bash
      run: |
        $OS_ROOT_DIR/EnergyPlus/energyplus --help

    - name: Classic Ruby CLI test
      shell: bash
      run: |
        set -x
        openstudio $CLASSIC_SUBCOMMAND --help
        openstudio $CLASSIC_SUBCOMMAND openstudio_version
        openstudio $CLASSIC_SUBCOMMAND energyplus_version
        openstudio $CLASSIC_SUBCOMMAND ruby_version
        openstudio $CLASSIC_SUBCOMMAND -e "puts OpenStudio::Model::Model.new()"
        openstudio $CLASSIC_SUBCOMMAND -e "require 'oga'; puts Oga::VERSION"
        openstudio $CLASSIC_SUBCOMMAND execute_ruby_script test.rb -x arg2
        openstudio $CLASSIC_SUBCOMMAND run -w compact_ruby_only.osw

    - name: C++ Labs CLI Test
      shell: bash
      run: |
        set -x
        openstudio $LABS_SUBCOMMAND --help
        openstudio $LABS_SUBCOMMAND openstudio_version
        openstudio $LABS_SUBCOMMAND energyplus_version
        openstudio $LABS_SUBCOMMAND ruby_version
        openstudio $LABS_SUBCOMMAND python_version
        openstudio $LABS_SUBCOMMAND -e "puts OpenStudio::Model::Model.new()"
        openstudio $LABS_SUBCOMMAND -e "require 'oga'; puts Oga::VERSION"
        openstudio $LABS_SUBCOMMAND execute_ruby_script test.rb -x arg2
        openstudio $LABS_SUBCOMMAND run -w compact_ruby_only.osw
        openstudio $LABS_SUBCOMMAND run -w compact_python_only_twomeasures.osw
        openstudio $LABS_SUBCOMMAND run -w compact_ruby_then_python.osw
        openstudio $LABS_SUBCOMMAND run -w compact_python_then_ruby.osw

    - uses: actions/setup-python@v5
      with:
        python-version: '3.8.x'

    - name: test loading the bindings in system python
      working-directory: ${{ env.OS_DIR_NAME }}
      run: |
        python --version
        python -c "from pathlib import Path; p = Path('./Python').absolute(); print(p); import sys; sys.path.insert(0, p.as_posix()); import openstudio; print(openstudio.openStudioLongVersion())"

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: test loading the bindings in system ruby
      shell: bash
      run: |
        ruby --version
        ruby -I$OS_ROOT_DIR/Ruby/ -e "require 'openstudio'; puts OpenStudio.openStudioLongVersion()"

    - name: Print OS SDK tree
      if: ${{ always() }}
      working-directory: ${{ env.OS_DIR_NAME }}
      run: |
        tree /f /a
